---
- name: Mettre à jour les paquets système
  apt:
    update_cache: yes
    upgrade: yes

- name: Installer les dépendances de base
  apt:
    name:
      - curl
      - wget
      - git
      - nano
      - python3
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
